attributes:
  snmp_polling_port:
    type: "text"
    weight: 10
    value: "161"
    label: "Polling Port"
    description: "Enter the port to accept polling events on"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  snmp_location:
    type: "text"
    weight: 20
    value: ""
    label: "System location"
  snmp_contact:
    type: "text"
    weight: 30
    value: ""
    label: "System contact"
  snmp_read_community:
    type: "text"
    weight: 40
    value: "public"
    label: "Read Community"
    description: "Enter the read-only community name"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  snmp_monitor_host:
    type: "text"
    weight: 50
    value: ""
    label: "Monitoring Host"
    description: "Enter the ip address of the monitoring host"
